### ISSUE TITLE
can you please demonstrate how to make post requests .i.e. communicate to server using ddd or clean architecture ? 

### ISSUE THREAD

**Issue by vrushangdev** [mhadaily/flutter-architecture-ddd#1]
Thanks for your efforts you are light of knowledge for new developers like us :) .

**Comment by mhadaily** [comment]
Hi and thanks @vrushangdev  for your kind words,

Sorry I have been a bit busy recently, I will absolutely update this repo very soon with new packages and fully working application within a few days. 

will keep you posted.

**Comment by vrushangdev** [comment]
wohooo , i am excited to learn more about clean architecture !!

**Comment by rafaelmpessoa** [comment]
im exciting too, waiting for update (:
